### ISSUE TITLE
Scan mods folder and add existing mods to profile

### ISSUE THREAD

**Issue by Grawl** [gorilla-devs/ferium#305] opened 2023-04-14 15:36 UTC
### The Problem

I have 57 mods in my `/mods` folder

I want to update them

I looking for a tool to automate updating of all these mods

I found Ferium

I have to manually grab ID from each mod to update them using Ferium

### Your Solution(s)

Provide ability to scan mods folder and try to add each of them to Ferium profile

**Comment by theRookieCoder** [comment] 2023-04-14 16:20
Duplicate of #57

**Closed by theRookieCoder** 2023-04-14 16:20 UTC
Labels: enhancement
