### ISSUE TITLE
Command colors aren't being displayed correctly

### ISSUE THREAD

**Issue by TheSpartaPT** [gorilla-devs/ferium#201] opened 2022-08-30 20:23 UTC
## Description
Colors seem to be bugged in certain commands.

## To Reproduce
the following are the commands where I know this problem is present, but there could be more.
`ferium add <mod>` (namely the messages talking about adding dependencies)
`ferium list`
`ferium profile list`
`ferium profile switch` (at least the error message saying "There is only 1 profile in your config")

## Software version
- Windows 11
- ferium 4.1.10 (installed through scoop)

## Additional information

Tested in both cmd and powershell, the result is the same

![image](https://user-images.githubusercontent.com/8343238/187535510-c6fce7e8-08aa-4b4b-b5f6-751a6cb56a3b.png)

**Comment by TheSpartaPT** [comment] 2022-08-31 00:30
This seems to be related btw: https://github.com/mackwic/colored/issues/110

**Comment by theRookieCoder** [comment] 2022-08-31 08:14
Duplicate of #148

**Closed by theRookieCoder** 2022-08-31 08:14 UTC
Labels: bug
