### ISSUE TITLE
Prevent manually added mods from being removed via ferium upgrade

### ISSUE THREAD

**Issue by Robinerra** [gorilla-devs/ferium#166] opened 2022-07-01 23:06 UTC
## The problem
Some mod developers, for whatever reason, wish their mods to not be downloaded by mod managers. The solution to this is to just manually download the mod and drag it into your mods folder, however running ferium upgrade will remove any mods not in the profile.json, meaning any manually downloaded mods will be removed.

## My solutions
Be able to add certain files or mods to a whitelist to avoid removal when upgrading.

**Comment by Robinerra** [comment] 2022-07-01 23:11
This would just be a temporary solution until #149 is implemented

**Comment by KyleUltimate** [comment] 2022-07-02 03:17
For your own profile, you can just throw the mods into need into user(which is in the mods folder), after running `ferium upgrade`, ferium you will have your mods in your mods folder! And well for modpacks? Ferium doesn't support user added mods yes

**Comment by theRookieCoder** [comment] 2022-07-02 14:34
Duplicate of #17

This feature is documented [here](https://github.com/gorilla-devs/ferium#adding-mods) under `External mods`

**Closed by theRookieCoder** 2022-07-02 14:34 UTC
Labels: enhancement
