### ISSUE TITLE
Some mods cause problems

### ISSUE THREAD

**Issue by misterhackerman** [gorilla-devs/ferium#450] opened 2024-12-11 10:22 UTC
### Description

CIT Resewn
when added by:
```
ferium add otVJckYQ
Successfully added CIT Resewn
ferium upgrade
Determining the Latest Compatible Versions

⠉ 8m [-----------------------------------] 0/76

```

and it keeps spining forever, in this case for 8 minutes and still. and when i remove this mod it works properly, this isn't the only one there are a few mods that i have installed causing the same behaviour.

### Steps to reproduce

```
ferium add otVJckYQ
ferium upgrade
```

### Operating System

Linux

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment] 2024-12-11 10:53
Duplicate of #432, I would recommend reverting to `v4.7.0` to fix this.

> when i remove this mod it works properly, this isn't the only one there are a few mods that i have installed causing the same behaviour

This behaviour isn't anything to do with the mods themselves, it's just that you are exceeding 75 mods, which triggers this bug.

**Closed** 2024-12-11 10:54 UTC
Labels: bug, duplicate

**Comment by misterhackerman** [comment] 2024-12-11 13:01
Thanks.
