### ISSUE TITLE
Unable to download certain mods (unknown variant `embedded`)

### ISSUE THREAD

**Issue by AliceDTRH** [gorilla-devs/ferium#171] opened 2022-07-17 13:50 UTC
## Description
*What is the bug?*
Some mods don't want to be added and throw an error message:
```shell
error decoding response body: unknown variant `embedded`, expected one of `required`, `optional`, `incompatible` at line 1 column 827
```

## To Reproduce
*What did you do to encounter this bug?*
```shell
$ ferium add preventer
```
Also happens with, among others: shulkertoolbox

## Software version
- OS (macOS/Windows/Linux)
Linux
```shell
$ lsb_release -a
LSB Version:	n/a
Distributor ID:	EndeavourOS
Description:	EndeavourOS Linux
Release:	rolling
Codename:	rolling
$ uname -r
5.18.6-zen1-1-zen
```

- Ferium Version (output of `ferium -V`)
```shell
$ ferium -V
ferium 4.1.5
```

**Comment by theRookieCoder** [comment] 2022-07-17 13:53
Duplicate of #169

Update to `4.1.6`

**Closed by theRookieCoder** 2022-07-17 13:53 UTC
Labels: bug
