### ISSUE TITLE
Download only server side mods.

### ISSUE THREAD

**Issue by jptrzy** [gorilla-devs/ferium#283] opened 2023-03-10 22:59 UTC
## The problem
I have a profile that I use on my client, but when I run it on my server,
client-site mods crashes it.

## My solutions
It could be quite helpful, if I could tell **ferium** to only **upgrade** server side mods.

**Comment by theRookieCoder** [comment] 2024-05-10 07:33
Duplicate of #143

**Closed by theRookieCoder** 2024-05-10 07:33 UTC
Labels: enhancement
