### ISSUE TITLE
Allow partial upgrades. Remember currently installed versions

### ISSUE THREAD

**Issue by imsofi** [gorilla-devs/ferium#176] opened 2022-07-19 15:50 UTC
## The problem
Currently the upgrade functionality of ferium lets you only do a full upgrade. Where all mods are installed and upgraded in one quick command. But sometimes keeping an old version may be a requirement for stability/support from another mod. Which can become quite a task to keep up on manually.

## My solutions
Update the `config.json` file to also carry sha256 hashes of the downloaded mods together with identifying tags (version number) from the relevant providers (Modrinth/Curseforge).

Let `ferium upgrade` take in optional identifier arguments to then only do a partial upgrade: `ferium upgrade lithium phosphor sodium`. One thing I am unsure of in this implementation is if that should also upgrade dependencies automatically. As maybe the latest `fabric-api` is problematic and you would like to target an older version, but `x` package has a dependency on it.

Relevant issue: #174

**Comment by imsofi** [comment] 2022-07-19 15:54
I would say to upgrade the dependencies automatically to avoid the risk of complicating the upgrade process. Rather adding in a  option like `--ignore <identifier>` when you know that a package is bad. But this may also want a "rollback" or CLI ability to retarget an older version of a broken jar.

Would love to hear from @theRookieCoder if you think this is an overly complicated thing that should be left out of ferium or something you would be interested in being a feature of ferium. As starting to think about package upgrades and downgrades as Individual components gets the project really close to what https://github.com/packwiz/packwiz is attempting to solve, and may not be in scope for what ferium is designed to be used for.

**Comment by theRookieCoder** [comment] 2022-07-19 16:01
Duplicate of #163, some interesting points about dependency management. Yes it might get really complicated, but we'll have to see because there are tons of enhancement suggestions related to version resolution, and we really have to properly consolidate them to create a system that makes sense.

**Closed by theRookieCoder** 2022-07-19 16:01 UTC
Labels: enhancement
