### ISSUE TITLE
Option to downgrade mod

### ISSUE THREAD

**Issue by T3sT3ro** [gorilla-devs/ferium#330] opened 2023-05-26 10:45 UTC
### The Problem

I didn't find that it's possible right now, but downgrading versions would be useful. Currently I am in a situation where the most recent sodium version is bugged and I gave to downgrade, but can't see that ferium uption: https://github.com/CaffeineMC/sodium-fabric/issues/1778

This relates to #82, because downgraded mods would have to be pinned and displayed differently on mod list.

### Your Solution(s)

Instead of removing the mod from list and having to add it to `user/`, a version pinning option that can be toggled for mods, an interactive selector for version of mod and a patch to updater where pinned versions are skipped.

**Comment by derspyy** [comment] 2023-05-26 17:13
the latest sodium on modrinth is `0.4.10`. so running `ferium upgrade` should use that. is that not the case?

**Comment by T3sT3ro** [comment] 2023-05-26 18:06
hmm, You are right, I do have sodium 0.4.10 pulled. Nonetheless, an option to downgrade and pin a mod would be nice (because earlier sodium 0.4.11 was present, and mod author removed the most recent version it was OK; if, however, author didn't remove the problematic version or it took some time, then ferium would pull the most recent, broken version).

**Comment by theRookieCoder** [comment] 2023-05-27 05:36
The Sodium Extra issue specifically would be fixed by either #82 or #196

Duplicate of #82. Just curious, but why did you decide to create this issue even if you knew this relates to #82 anyways?

**Closed** 2023-05-27 05:36 UTC
Labels: enhancement

**Comment by T3sT3ro** [comment] 2023-05-27 08:10
Hmm, probably a momentary brainfart 😅 I was thinking about "mod pinning" as a way to tell ferium "stop updating this mod untill unpinned". In here I was thinking about a subcommand that displays an interactive list of all compatible versions and lets user select one to pin.
