### ISSUE TITLE
"Add when compatible" for adding mods

### ISSUE THREAD

**Issue by superluig164** [gorilla-devs/ferium#307] opened 2023-04-15 19:35 UTC
### The Problem

For example, I find a mod that is not yet compatible with the version of Minecraft I'm playing on.  However it is reasonable to assume it will soon be updated to this version (ex. going from 1.19.2 to 1.19.3)  Right now I have to save a bookmark and keep checking it repeatedly.

### Your Solution(s)

In this case it would be pretty epic if Ferium could keep track of these mods, and continue to check them for compatibility whenever I do the "upgrade" option.  That way I can accumulate a list of mods that I want to have eventually, and I can be prompted to add them whenever they become compatible with this version.  By extension if I update Minecraft, and some of my existing mods are no longer compatible, they can be added to this list as well and re-added when they become compatible.  To remove them just use the existing remove command.

**Comment by theRookieCoder** [comment] 2023-04-16 05:06
Duplicate of #142

**Closed by theRookieCoder** 2023-04-16 05:06 UTC
Labels: enhancement
