### ISSUE TITLE
Add multiple mods at once

### ISSUE THREAD

**Issue by soupglasses** [gorilla-devs/ferium#175] opened 2022-07-19 15:42 UTC
## The problem
Currently the `ferium add` command only allows you to define one mod at a time. But more often than not you know that you want to add at least two mods into the profile.

## My solutions
Allow you to define multiple mods at once: `ferium add sodium lithium phosphor`

**Comment by theRookieCoder** [comment] 2022-12-07 14:02
If you're wondering why it's taking so long, the problem is that it's a little complicated to add multiple mods at once if you need to adjust the override flags. I'm thinking of a system of 'upgrading', i.e. determining the latest versions of the mods given, and then adjusting the overrides. This issue is also why scanning is taking so long to implement even though most of the backend work is done (thank you so much @tuxinal !)

**Comment by tippfehlr** [comment] 2023-05-16 16:45
how would you handle errors?
There are a few possible ways:

1. abort when an error is encountered (but add mods before the error)
2. keep adding the other mods after error
3. check all mods beforehand and only add them when all mods are valid

the big package managers (apt, pacman, etc.) seem to apply option 3.

I implemented option 2 and when I misspell a mod it’s convenient that the other mods are added nonetheless and I only have to add the misspelled one again though.

Option 1 seems like a bad Idea.

*I would treat already added mods like a success: The user’s intention is to add them, so the end result is correct.*

**Comment by theRookieCoder** [comment] 2023-05-17 10:50
Interesting question, my current plan is 2 because that's what is used when upgrading, and as you said I find it much more convenient. As for

> I would treat already added mods like a success: The user’s intention is to add them, so the end result is correct.

I will be changing already added to a warning without and exit code.

**Comment by imsofi** [comment] 2023-05-17 11:14
I would reccomend 3, as with 2 it would make your command order dependent on what gets created as output. For a `sodium doesnt-exist lithium` would flop on 2, only giving sodium. But if `doesnt-exist` comes first nothing gets installed, etc.

Error early, list the mod that had trouble. Do nothing. A failed command should not modify the mods folder on purpose. A good nicety would be to list all mods that failed to fetch instead of raising on first error. But this can get tricky to implement.

**Comment by imsofi** [comment] 2023-05-17 12:16
Yeah sorry. I was explaining 1 but accidentally called it 2. But my idea that 3 would likely be the best to avoid issues and not have the case where "oh i hit an error in the tooling and now its put my modpack in a corrupt state with missing dependencies".

You can call the argument `--keep-going` to turn on the second mode. It should at least avoid any accidental copy pastes and make it clear that it will keep going.

**Comment by theRookieCoder** [comment] 2023-05-17 12:38
Haha no problem.

> As it makes it clear that errors do not change state

I think this is a fair point since this is the approach I took for removing mods too. However we have to remember that for things like directory scanning, it's very normal and expected to have some mods that can't be added, e.g. because they couldn't be found, have 3rd party access restricted, are not compatible, etc.

I haven't decided the exact flow when adding multiple mods since there needs to be a way to troubleshoot incompatible mods, I'll have to experiment with options 2 and 3.

**Comment by tippfehlr** [comment] 2023-05-17 12:52
I think implementing 2 is enough for a mod manager. Option 3 needs a totally different approach (chenking mods first) and doing it as a command line flag seems a bit unnecessary to me.

**Comment by theRookieCoder** [comment] 2024-02-24 14:39
I have added preliminary support for this in 40a1043

It is functional, but it's slow and makes too many network requests for my liking (~2 for every mod)

**Comment by theRookieCoder** [comment] 2024-06-10 14:14
I've made this use batch requests in gorilla-devs/libium@130055b78b47eb6e91cc0642b3f485ecb66b2bba. One awesome improvement is that the compatibility checks are performed using data from these same batch requests. So no matter how many mods you add, there will only be a maximum of 3 requests made (one for each platform).

**Comment by theRookieCoder** [comment] 2024-06-10 18:08
Fixed in 3baa0c64bc558c77890fdccf075d88bd155cc16b

**Closed by theRookieCoder** 2024-06-10 18:08 UTC
Labels: enhancement, priority, fixed in source
