### ISSUE TITLE
Option to disable "project is not a mod" error

### ISSUE THREAD

**Issue by redstonerti** [gorilla-devs/ferium#243] opened 2022-12-06 18:27 UTC
## The problem
I want to use ferium to manage shaders.

## My solutions
I don't need anything else from the project other than to be able to disable the "project is not a mod" error. If I could do that, I could have different profiles for shaders and different profiles for mods and update everything accordingly.
Thanks.

I am aware that there is a similar issue and the answer to that was to add it to the backlog. I am asking for something a bit simpler, and so I thought it warranted its own issue.

**Comment by theRookieCoder** [comment] 2022-12-07 13:34
Duplicate of #141

Sorry but supporting different types of projects is a bit more complicated than just disabling the mod check.

**Closed by theRookieCoder** 2022-12-07 13:34 UTC
Labels: enhancement
