### ISSUE TITLE
Recursive mod dependency search

### ISSUE THREAD

**Issue by kyee-rs** [gorilla-devs/ferium#393] opened 2023-12-02 21:25 UTC
### The Problem

When you download any mod and say `"yes"` on any optional dependency, it will download only the optional dependency mod itself, completely ignoring mods that "_**OPTIONAL DEPENDENCY**_" depends on.

### Your Solution(s)

Recurive search of dependencies of dependencies.

**Comment by theRookieCoder** [comment] 2023-12-03 05:35
Duplicate of #214

**Closed by theRookieCoder** 2023-12-03 05:35 UTC
Labels: enhancement
