### ISSUE TITLE
Error decoding response body on curseforge

### ISSUE THREAD

**Issue by owosoup** [gorilla-devs/ferium#297] opened 2023-03-29 18:58 UTC
When running ``ferium add <curseforge mod ID>``, I get this error message:

``error decoding response body: unknown field `latestEarlyAccessFilesIndexes`, expected one of `id`, `gameId`, `name`, `slug`, `links`, `summary`, `status`, `downloadCount`, `isFeatured`, `primaryCategoryId`, `categories`, `classId`, `authors`, `logo`, `screenshots`, `mainFileId`, `latestFiles`, `latestFilesIndexes`, `dateCreated`, `dateModified`, `dateReleased`, `allowModDistribution`, `gamePopularityRank`, `isAvailable`, `thumbsUpCount` at line 1 column 5764``

Note that the number at the end varies for every mod ID, this is the one for Resolution Control, ID 632729. 
It seems to change with time as well.

**Comment by theRookieCoder** [comment] 2023-03-30 05:16
Duplicate of #290 

Update to [`v4.4.0`](https://github.com/gorilla-devs/ferium/releases/tag/v4.4.0) to fix this.

**Closed by theRookieCoder** 2023-03-30 05:16 UTC
