### ISSUE TITLE
Add mods to modpack

### ISSUE THREAD

**Issue by abhemanyus** [gorilla-devs/ferium#183] opened 2022-07-28 15:46 UTC
## The problem
Adding a mod to the same directory that has a modpack (also installed via ferium), removes all the mods from that modpack.

## My solutions
Ability to add mods to a modpack without removing the existing mods.

**Comment by theRookieCoder** [comment] 2022-07-28 15:49
Duplicate of #94

**Closed by theRookieCoder** 2022-07-28 15:49 UTC
Labels: enhancement
