### ISSUE TITLE
Show version changes during `upgrade`

### ISSUE THREAD

**Issue by Henryws** [gorilla-devs/ferium#220] opened 2022-10-23 13:05 UTC
## The problem
I would like to be able to see the version changes when running `ferium upgrade`. Currently it just downloads them.

## My solutions
Log the current version, check for upgrades, display the version changes side by side, then upgrade

**Comment by theRookieCoder** [comment] 2022-10-23 15:09
Duplicate of #49

**Closed by theRookieCoder** 2022-10-23 15:09 UTC
Labels: enhancement
