### ISSUE TITLE
Force ignore compability issue

### ISSUE THREAD

**Issue by youth0530** [gorilla-devs/ferium#424] opened 2024-07-29 10:27 UTC
### The Problem

I'm using Sinytra connector and I can't install the incompatibility mod,
It may inconvenience the user who is using a special environment.

### Your Solution(s)

For example:
- Allow to select multiple version (and mod loader)
- Ignore the incompatibility option in the add subcommand
- Add new mod loader "Sinytra connector" (not recommended)

**Comment by theRookieCoder** [comment] 2024-07-30 13:20
> Ignore the incompatibility option in the add subcommand

You can use the `--force` or `--override` options. I haven't documented this flag in the readme yet, but the feature does exist.

```
# ferium help add
Add mods to the profile

...

Options:
  -f, --force
          Temporarily ignore game version and mod loader checks and add the mod anyway
          
          [aliases: override]
```

**Comment by theRookieCoder** [comment] 2024-07-30 13:21
Duplicate of #142

**Closed by theRookieCoder** 2024-07-30 13:21 UTC
Labels: duplicate, enhancement
