### ISSUE TITLE
Add option to add mod as soon as its compatible

### ISSUE THREAD

**Issue by otter501** [gorilla-devs/ferium#278] opened 2023-02-15 03:59 UTC
## The problem
Some mods I want to use aren't on my version so I have to wait until they are, the problem is that I have to either find out manually or edit the config and have an error whenever I update,

## My solutions
Add a parameter like --queue or something like that.

**Comment by theRookieCoder** [comment] 2023-02-15 04:02
Duplicate of #142

Btw it's normal to leave uncompatible mods in your profile since them not resolving doesn't actually affect other mods downloading.

**Closed** 2023-02-15 04:02 UTC
Labels: duplicate, enhancement
