### ISSUE TITLE
Cache mods 

### ISSUE THREAD

**Issue by K4LCIFER** [gorilla-devs/ferium#357] opened 2023-06-29 01:14 UTC
### The Problem

When changing to the mods contained in a separate profile, the mods are re-downloaded each time. 

### Your Solution(s)

If the mods for that profile are cached, it would be as simple as just internally switching to that profiles folder that contains the mods, instead of manually re downloading them each time. Could even just interanally change symbolic links.

**Comment by theRookieCoder** [comment] 2023-06-29 08:37
Duplicate of #109

**Closed as not planned by theRookieCoder** 2023-06-29 08:37 UTC
