### ISSUE TITLE
Add possibility to enforce specific mod version

### ISSUE THREAD

**Issue by JeremyDarbellay** [gorilla-devs/ferium#318] opened 2023-05-14 07:35 UTC
### The Problem

When upgrading, sometimes, mod upgrade cause conflict. Atm, sodium extra. 
I would like to be able to enforce a specific version of this mod, without removing it, then adding manually this version to user folder, then undoing all of that.

### Your Solution(s)

Command, and/or config can be : `ferium add <mod>:<version>`, for removing just `ferium add <mod>`
 or `ferium add-version <mod> <version>` and so on `ferium remove-version <mod>` 
This can be an advanced functionality, so maybe just put a field in config.json like this :
```json
{
  "name": "abc",
  "identifier": {
    "TypeOfProject": "slug"
  },
  "use-version": "<version>"
}
```

I don't know how you check version, so don't know how to format "version".

Have a good day !

**Comment by theRookieCoder** [comment] 2023-05-14 07:59
Duplicate of #82

**Closed by theRookieCoder** 2023-05-14 07:59 UTC
Labels: enhancement
