### ISSUE TITLE
GitLab Support

### ISSUE THREAD

**Issue by plfrmr** [gorilla-devs/ferium#410] opened 2024-03-23 18:43 UTC
### The Problem

I was trying to add DistantHorizons GitLab page but it didn't work.
![Screenshot_21](https://github.com/gorilla-devs/ferium/assets/71834662/c967ff59-3939-41be-abdb-ec3aa914cc67)

### Your Solution(s)

Maybe you could add gitlab builds support?

**Comment by theRookieCoder** [comment] 2024-03-23 18:45
Duplicate of #188

**Closed by theRookieCoder** 2024-03-23 18:45 UTC
Labels: enhancement
