### ISSUE TITLE
Pick specific version of mod

### ISSUE THREAD

**Issue by DuendeInexistente** [gorilla-devs/ferium#177] opened 2022-07-21 02:40 UTC
## The problem
Currently, Debugify's latest version crashes with Lithium.

## My solutions
Being able to pick which version one uses, and maybe telling ferium to skip a specific version.

**Comment by theRookieCoder** [comment] 2022-07-21 12:35
Duplicate of #82

**Closed by theRookieCoder** 2022-07-21 12:35 UTC
Labels: enhancement
