### ISSUE TITLE
Can't set modpack version

### ISSUE THREAD

**Issue by sarim** [gorilla-devs/ferium#128] opened 2022-06-09 17:50 UTC
## Description
Cannot set modpack version. (Using modrinth modpack).

## To Reproduce
`ferium modpack upgrade`

## Software version
- Windows
- ferium 4.1.2

## Additional information

N/A

**Comment by theRookieCoder** [comment] 2022-06-10 12:06
Duplicate of #82

**Closed by theRookieCoder** 2022-06-10 12:06 UTC
Labels: bug, duplicate
