### ISSUE TITLE
Winget release cannot download modpack

### ISSUE THREAD

**Issue by Lancelotbronner** [gorilla-devs/ferium#436] opened 2024-10-23 04:07 UTC
### Description

I'm trying to install Monifactory from CurseForge, `ferium add 1004602` worked fine then `ferium modpack install` reports 3 mods that cannot be automatically downloaded but then gets stuck waiting to download the 193 others, stays at 0 bytes downloaded.

### Steps to reproduce

1. Install via `winget`
2. `ferium add 1004602`
3. `ferium modpack install`

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

### Additional Information

Stays stuck on this forever:
```
> ferium modpack install

Determining files to download... ✓ Fetched 196 mods

The following mod(s) have denied 3rd parties such as Ferium from downloading it
- Fix Experience Bug (now with FABRIC and FORGE versions)
  https://www.curseforge.com/minecraft/mc-mods/fix-experience-bug/download/4587408
- AntiBlocksReChiseled
  https://www.curseforge.com/minecraft/mc-mods/antiblocksrechiseled/download/5642039
- Entity Culling Fabric/Forge
  https://www.curseforge.com/minecraft/mc-mods/entityculling/download/5672088

Downloading 193 Mod Files

⠂ 0 B/s [-----------------------------------------------------------------------------------------------] 0 B/201.53 MiB
```

**Comment by edoren** [comment] 2024-10-26 15:48
Hello, I'm having the same issue using the cargo version on Windows

**Comment by theRookieCoder** [comment] 2024-10-26 17:24
Duplicate of #432

The bug was introduced in the latest update, you can either downgrade to 4.7.0 (there are no functionality changes or bug fixes between the 2), build from https://github.com/gorilla-devs/ferium/tree/main, or get the latest successful build asset from https://github.com/gorilla-devs/ferium/actions/workflows/build.yml.

**Closed by theRookieCoder** 2024-10-26 17:24 UTC
Labels: bug
