### ISSUE TITLE
Curseforge download error

### ISSUE THREAD

**Issue by BlackBaroness** [gorilla-devs/ferium#294] opened 2023-03-27 11:59 UTC
```
> ferium add 336018
Adding mod... error decoding response body: unknown field `latestEarlyAccessFilesIndexes`, expected one of `id`, `gameId`, `name`, `slug`, `links`, `summary`, `status`, `downloadCount`, `isFeatured`, `primaryCategoryId`, `categories`, `classId`, `authors`, `logo`, `screenshots`, `mainFileId`, `latestFiles`, `latestFilesIndexes`, `dateCreated`, `dateModified`, `dateReleased`, `allowModDistribution`, `gamePopularityRank`, `isAvailable`, `thumbsUpCount` at line 1 column 8497
```

## Software version
- OS - Linux
- Ferium Version - 4.3.4

**Comment by theRookieCoder** [comment] 2023-03-27 12:00
Duplicate of #290

**Comment by theRookieCoder** [comment] 2023-03-27 12:01
> Ferium Version - 4.3.4

Update to [`v4.4.0`](https://github.com/gorilla-devs/ferium/releases/tag/v4.4.0) to fix this.

**Closed by theRookieCoder** 2023-03-27 12:00 UTC
Labels: bug
