### ISSUE TITLE
Issue involving mods from CurseForge

### ISSUE THREAD

**Issue by Degenerate-Peanut** [gorilla-devs/ferium#293] opened 2023-03-24 04:44 UTC
## Description
Ferium prints an error message in PowerShell when I attempt to download any mod from CurseForge, It doesn't happen when I download from the either two sources, just Forge sourced mods, that usually aren't on the other two
## To Reproduce
I used the ferium add command (Example: ferium add <Forge Code/Mod Name>)
## Software version
- OS Windows 11
- Ferium Version 4.3.4
## Additional information
Used in combination with Fabric version 0.11.2 and Minecraft Java edition (1.19.3 Release)
![image_2023-03-24_154351031](https://user-images.githubusercontent.com/113686096/227426426-8b689578-c581-442d-b8c0-5904aff8fe28.png)

**Comment by theRookieCoder** [comment] 2023-03-24 04:46
Duplicate of #290

I will be releasing the fix today

**Closed by theRookieCoder** 2023-03-24 04:46 UTC
Labels: bug
