### ISSUE TITLE
Defer game version check to upgrade phase

### ISSUE THREAD

**Issue by Tomasan7** [gorilla-devs/ferium#257] opened 2023-01-01 12:12 UTC
## The problem
Sometimes, a mod you want to download isn't updated to the minecraft version you want **yet**. But you want to add it to the ferium and once the mod dev releases a version for your target game version, it gets downloaded with the `upgrade` command.

## My solutions
Instead of checking the game version when you add the mod. Check the version when you run `upgrade`.

**Comment by theRookieCoder** [comment] 2023-01-01 13:16
Duplicate of #142

**Closed by theRookieCoder** 2023-01-01 13:16 UTC
Labels: duplicate, enhancement
