### ISSUE TITLE
Some mods could have more than 1 artifact for the same game/mod version. There is no way to select which one to use.

### ISSUE THREAD

**Issue by sharkman** [gorilla-devs/ferium#298] opened 2023-04-05 12:42 UTC
## Description
Some mods could have more than 1 artifact for the same game/mod version.
There is no way to select which one to use.
For example mod "Your Reputation" on Curseforge has 2 different artifacts for different implementations of WAYLA:
WTHIT: https://www.curseforge.com/minecraft/mc-mods/your-reputation/files/4447651
jade:     https://www.curseforge.com/minecraft/mc-mods/your-reputation/files/4447652

## To Reproduce
Add "Your Reputation" to mod list, it will select implementation with jade automatically.

## Software version
- Windows 10
- ferium 4.4.0

**Comment by theRookieCoder** [comment] 2023-04-05 13:44
Duplicate of #95

Also #155 should allow you to specify a glob or regex pattern so that you can automatically select the WTHIT or Jade version.

**Closed by theRookieCoder** 2023-04-05 13:44 UTC
Labels: bug
