### ISSUE TITLE
Purging old dependancies

### ISSUE THREAD

**Issue by jesperls** [gorilla-devs/ferium#368] opened 2023-08-26 09:45 UTC
### The Problem

Currently when I remove a mod which added a dependancy mod, the dependancy mod stays while the mod gets removed and it stays there cluttering the modlist.

### Your Solution(s)

"ferium purge" a command which check mods added as dependancies and removes ones that are no longer necessary.

**Comment by theRookieCoder** [comment] 2023-08-26 10:51
Duplicate of #258, see my reply there for why I'm not planning on using your suggested solution.

**Closed by theRookieCoder** 2023-08-26 10:51 UTC
Labels: enhancement

**Comment by jesperls** [comment] 2023-08-26 11:01
> Duplicate of #258, see my reply there for why I'm not planning on using your suggested solution.

oh my bad, yeah that sounds like a way cleaner solution
