### ISSUE TITLE
MSVC version ANSI escape codes bugged on installing message

### ISSUE THREAD

**Issue by codethinki** [gorilla-devs/ferium#387] opened 2023-11-17 20:00 UTC
### Description

the ansi escape codes are messed up maybe u put the escape character after [...m because there is this ? mark symbol after it. Seems to be bugged on [2m [1m [32m maybe more idk.
![image](https://github.com/gorilla-devs/ferium/assets/89145039/06726ae0-0c5a-40e0-9f8f-40d23358d1df)

### Steps to reproduce

ferium add ...
ferium add (something invalid)

### Operating System

Windows

### Are you using the latest version of ferium?

- [X] I am using the latest version of ferium

**Comment by theRookieCoder** [comment] 2023-11-24 14:49
Duplicate of #148
If you're on Windows 10 or newer, I highly recommend using microsoft/terminal instead

**Closed by theRookieCoder** 2023-11-24 14:49 UTC
Labels: bug
