### ISSUE TITLE
Add a log file and log actions

### ISSUE THREAD

**Issue by Genious28** [gorilla-devs/ferium#64] opened 2022-05-12 11:55 UTC
1. Logging.
2. Support for Packs (Modpacks, ResourcePacks, TexturePacks, ShaderPacks, DataPacks) especially Modpacks.
3. Remove Duplicates from an existing Mod Folder.
4. Scan Directory Feature, meaning that it would scan each file, if their name is understandable (Not like 'MmmMmmMmm.jar' for 'Test Dummys' Mod), use the old .jar Mod File Names to look for newer versions and upgrade them? but i guess you'll need a database for that though.. to find IDs out of Mod/File Names
5. Scan List Feature, this would simply scan Names or IDs listed in a .txt or .xlsx file, and iterate through each and every one.. And all issues shall be logged into a .txt file. That will help find conflicts, Version issues etc.

**Comment by theRookieCoder** [comment] 2022-05-12 12:04
1. This is quite ambiguous, what exactly should this do?
2. Modpack support is planned in #5, this is a mod manager so I do not plan on supporting other types of 'modifications'
3. I don't understand this either, what exactly should this do?
4. Duplicate of #57
5. I'm not sure why someone would need this if #57 is implemented, but I guess it would be nice. Maybe from a list of website URls?

Thanks for the suggestions!

**Comment by Genious28** [comment] 2022-05-12 12:18
1. Simply log each action.. You can simply make that by creating a Function that simply takes the following items as Arguments and writes them into a file; 

- System Time
- Mod Name
- Action to be performed
- Action Result (Success, Fail)
- Possibly even the cause of Failure 

2. Understood, they really should add more information about other types of modifications.

3. Well, it would simply 'Clean' your existing Mod Folder that you specify the path to... Removing Duplicates as well as Unsupported Versions (If the Profile is 1.18.2 and a particular mod exists for that version, remove all others unless their version is ignored in the Config File and the latest doesn't exist)

4. Yea, it could also work as a reference.. Take the Existing Mod Names as Reference, get their newer or respective versions to the profile and put them into a new Profile.

5. Getting a list of URLs will be too tedious for anyone.. i had 250 Mods, Thankfully i've made a Collection for all their Download Links. i used that to get the IDs and put them into a .xlsx file.

- Now, using that as a list of mods that a user wants to install would be really helpful. Rather than typing the command repeatedly with different IDs, why not iterate through rows, grab each ID into a variable and execute the `ferium add-curseforge <ID>` replacing the <ID> with the variable_ID. Essentially automatically downloading a list of mods using a list of IDs instead of manually typing the command repeatedly.

**Comment by theRookieCoder** [comment] 2022-05-12 12:27
1. Sure I'll consider that

3. Doing things to your existing mods is not something Ferium is going to do (the only exception is #57). In fact once you start using Ferium, the idea is that you should never edit the output directory

6. Byt that I meant either a link or a list of IDs, this would be possible due to regexes

**Comment by Genious28** [comment] 2022-05-12 12:31
Noice.. Logging will help you alot in debugging, as well as the users.

Ah, okay.. it would be helpful though, 'cause it's a mod manager. :P
It's okay tho..

Yeap, both could work.. Not really, you simply need to iteratively take input commands from a file, that's all.

**Comment by theRookieCoder** [comment] 2022-06-04 15:13
Honestly, a log file is quite overkill. I think we should solve the root problem, which is that the error messages are terrible and don't actually tell you _where_ the error occurred. Something like a stacktrace. Moved to #116

**Closed by theRookieCoder** 2022-06-04 15:13 UTC
Labels: enhancement
