### ISSUE TITLE
Can Ferium search for modpacks on Curseforge?

### ISSUE THREAD

**Issue by ryankhart** [gorilla-devs/ferium#281] opened 2023-02-26 13:52 UTC
Can Ferium search for modpacks on Curseforge by filtering for desired mods and sorting by download count? Or is that beyond the scope of this project?

I recently got approved for my own Curseforge API key for a project to search for and print a list of all modpacks that contained a specified list of mods and then sort that list of modpacks by download count or ideally "popularity".

As I am a little inexperienced dealing with APIs, I found their official API documentation confusing. So I started looking for example projects on GitHub. And this looks like a very exciting project.

This issue can either be considered a feature request or closed altogether, but I would greatly appreciate some guidance on whether or not Curseforge permits such activities through their API. It is worth noting that there is no mention of "modpacks" on the official Curseforge API documentation website (https://docs.curseforge.com/).

**Comment by theRookieCoder** [comment] 2023-03-23 11:07
Duplicate of #189

It is possible to implement a search feature using purely the official API, however my reasoning for not implementing it yet is that a CLI search interface would be very difficult (if not at all possible) to get right. The websites have perfectly good search functionality anyways, so it's not a priority of mine either.

**Closed** 2023-03-23 11:08 UTC
Labels: enhancement
