### ISSUE TITLE
Mod version specifier

### ISSUE THREAD

**Issue by ItsJasperHere** [gorilla-devs/ferium#272] opened 2023-02-06 20:57 UTC
## The problem
Is your feature request related to a problem? Please describe it.
Mods sometimes require specific mod versions. (An example of this is Iris Shaders requiring 0.4.8, instead of the newest version which is 0.4/9
## My solutions
Describe any number of solutions you've thought of.
Add another command argument so that people can decide which version they would like to download

**Comment by theRookieCoder** [comment] 2023-02-07 09:08
Duplicate of #82

**Closed** 2023-02-07 09:09 UTC
Labels: duplicate, enhancement
