### ISSUE TITLE
[BUG] Modpacks cannot be imported

### ISSUE THREAD

**Issue by KavyanshKhaitan2** [gorilla-devs/ferium#447] opened 2024-12-01 10:42 UTC
### Description

Running the commands (given below in the `Steps to reproduce` category) doesnt download anything and hangs at 0 bytes downloaded.

I am trying to download the Vault Hunters 3rd Edition Modpack (https://www.curseforge.com/minecraft/modpacks/vault-hunters-1-18-2).

![image](https://github.com/user-attachments/assets/9145d87e-f903-4e0a-9183-4a7aaff3ced5)
Above is a screenshot from `taskmgr`. This shows that ferium is indeed not downloading anything (zero network traffic).

Any help is very appreciated!

### Steps to reproduce

```shell

C:\Users\User\Desktop\ferium>ferium modpack add 711537
Checking modpack... ✓ (Vault Hunters 3rd Edition)
Where should the modpack be installed to?
✔ Output Directory · \\?\C:\UltimMC\instances\Vault Hunters\.minecraft
There are files in the mods folder in your output directory, these will be deleted when you upgrade.
✔ Would like to create a backup? · no
✔ Should overrides be installed? · yes
WARNING: Files in your output directory may be overwritten by modpack overrides

C:\Users\User\Desktop\ferium>ferium modpack upgrade

Determining files to download... ✓ Fetched 151 mods

The following mod(s) have denied 3rd parties such as Ferium from downloading it
- Neon Craft 2 Mod
  https://www.curseforge.com/minecraft/mc-mods/neon-craft-2-mod/download/3726051
- Vault Hunters Jewel Sorting
  https://www.curseforge.com/minecraft/mc-mods/vault-hunters-jewel-sorting/download/5585222

Downloading 149 Mod Files

⠂ 0 B/s [-----------------------------------------------------------------------------------------------------------------------------------------------] 0 B/225.83 MiB
``` 

### Operating System

Windows

### Are you using the latest version of ferium?

- [x] I am using the latest version of ferium

**Comment by theRookieCoder** [comment] 2024-12-03 05:19
Duplicate of #432, use `v4.7.0` in the meantime.

**Closed by theRookieCoder** 2024-12-03 05:19 UTC
Labels: bug
