### ISSUE TITLE
Support for paper plugins

### ISSUE THREAD

**Issue by HoldYourWaffle** [gorilla-devs/ferium#431] opened 2024-09-14 00:55 UTC
### The Problem

It'd be great if I could use ferium to manage the plugins for paper-based servers as well.

### Your Solution(s)

This relates to #90 and #425, but at the core the mechanics for paper are the same as the other modloaders.

**Comment by theRookieCoder** [comment] 2024-09-14 05:36
Duplicate of #275

**Closed by theRookieCoder** 2024-09-14 05:36 UTC
Labels: enhancement

**Comment by HoldYourWaffle** [comment] 2024-09-14 09:30
Whoooops, I shouldn't make issues at 3am...
