### ISSUE TITLE
Allow specific mod dependancies to be disabled

### ISSUE THREAD

**Issue by slushie0** [gorilla-devs/ferium#239] opened 2022-12-03 01:43 UTC
## The problem
I am using the quilt mod loader, and whenever I download a fabric mod (which are compatible with quilt) It downloads the Fabric API because it's listed as a dependency. Then I have to manually remove it every time this happens.

## My solutions
Add an option to disable the auto-downloading of dependencies, or rather just don't download the Fabric API specifically when using the Quilt loader.

**Comment by theRookieCoder** [comment] 2022-12-03 12:16
> Add an option to disable the auto-downloading of dependencies

You can do this using the `--dependencies none` option in the add command (see the add command's help page for details)

Duplicate of #127

**Closed by theRookieCoder** 2022-12-03 12:16 UTC
Labels: enhancement

**Comment by slushie0** [comment] 2022-12-03 16:47
But then other required dependencies don't get downloaded. All dependencies should be installed _except_ for Fabric API

**Comment by theRookieCoder** [comment] 2022-12-03 16:49
Yes exactly, that's just the workaround I provided because you had suggested it. The last line says that this issue is a duplicate of #127

**Comment by slushie0** [comment] 2022-12-03 17:02
Oh, sorry. When I was typing that I meant to say "Add an option to disable the auto-downloading of _certain_ dependencies.
