### ISSUE TITLE
Confirm with the user before downloading mods

### ISSUE THREAD

**Issue by DarkShadow44** [gorilla-devs/ferium#162] opened 2022-07-01 11:33 UTC
## The problem
Sometimes it would be nice to now what mods have updates available, so I can check before updating them all.

## My solutions
Add listing for all upgradable mods.

**Comment by Eskaan** [comment] 2022-07-01 11:37
Add `--pretend` option to the upgrade subcommand

**Comment by DarkShadow44** [comment] 2022-07-01 11:43
I assume this a suggestion how to implement it, not something that should already work?

**Comment by theRookieCoder** [comment] 2022-07-01 11:57
Would be resolved by #49
Basically normally there will be a y/n prompt. If `--force` is used, it will download all the files no matter what, and if `--dry-run` is used, it will stop after version resolution and won't download anything.

**Comment by theRookieCoder** [comment] 2023-03-24 12:01
Duplicate of #49

**Closed by theRookieCoder** 2023-03-24 12:01 UTC
Labels: enhancement
