### ISSUE TITLE
`Not a terminal` error when toggling Caps Lock in Windows

### ISSUE THREAD

**Issue by sitiom** [gorilla-devs/ferium#182] opened 2022-07-25 05:21 UTC
## Description
When trying to name my profile using the `ferium profile create` command and toggling the Caps Lock key, ferium exits out with a `Not a terminal` error.

## To Reproduce
- `ferium profile create`
- Toggle caps lock on the `What should this profile be called?` prompt.

## Software version
- Windows 11
- ferium 4.1.8

## Additional information
See video:

https://user-images.githubusercontent.com/56180050/180703692-e64e64ca-8ec9-45f8-9cb7-d4477be1afea.mp4

**Comment by theRookieCoder** [comment] 2022-07-25 12:37
Unable to replicate on macOS, I will try on Windows 11 later. This is probably related to dialoguer though.

**Comment by theRookieCoder** [comment] 2022-07-25 12:39
This should have been fixed on mitsuhiko/dialoguer#192, not sure what the problem is.

**Closed** 2023-03-24 12:00 UTC
Labels: bug
