### ISSUE TITLE
Index out of bounds in some cases after deleting a profile

### ISSUE THREAD

**Issue by Obiuzera** [gorilla-devs/ferium#232] opened 2022-11-16 21:38 UTC
## Description
When deleting a profile the value `active_profile` in config.json remains unchanged.
If the last profile of the array was active before deleting a profile, this results in an out of bounds error:
```
thread 'main' panicked at 'index out of bounds: the len is 1 but the index is 1', ~/.cargo/registry/src/github.com-1ecc62
99db9ec823/ferium-4.2.0/src/main.rs:400:17                                                                                         
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## To Reproduce
* ```ferium profile create``` lets call this Profile-A
* ```ferium profile create``` lets call this Profile-B
* ```ferium profile switch``` ensure Profile-B is active
* ```ferium profile delete``` delete Profile-A
* ```ferium upgrade``` should now throw an Index out of bounds error
* ~/.config/ferium/config.json has ```"active_profile": 1```, should be 0

## Software version
- Fedora 36
- Ferium 4.2.0

**Comment by theRookieCoder** [comment] 2022-11-17 14:33
Duplicate of #229, please update ferium to the latest version

**Closed by theRookieCoder** 2022-11-17 14:33 UTC
Labels: bug
