### ISSUE TITLE
Auto Import

### ISSUE THREAD

**Issue by MIPOHBOPOHIH** [gorilla-devs/ferium#237] opened 2022-11-22 19:15 UTC
What are some ways to automatically import mods from .mods?
![Uploading image.png…]()

**Comment by MIPOHBOPOHIH** [comment] 2022-11-22 19:15
![image](https://user-images.githubusercontent.com/98014624/203401933-2a758bb4-a644-4ce5-8f51-1e455029a654.png)

**Comment by theRookieCoder** [comment] 2022-11-23 12:24
Duplicate of #57

Unfortunately there is no solution as of now

**Closed by theRookieCoder** 2022-11-23 12:24 UTC
