### ISSUE TITLE
Allow downloading "incompatible" versions of mods

### ISSUE THREAD

**Issue by owopeachy** [gorilla-devs/ferium#407] opened 2024-02-26 18:55 UTC
### The Problem

The program does not seem to allow you do download mods it deems to be incompatible despite the available versions working perfectly fine even if theyre 1 or 2 versions behind

### Your Solution(s)

Please give us a bypass option that simply downloads the most recent release anyway and let us manually assess whether it crashes or not. I have a small mod list and can handle this myself

**Comment by theRookieCoder** [comment] 2024-02-27 06:48
Duplicate of #95

**Closed by theRookieCoder** 2024-02-27 06:48 UTC
Labels: enhancement

**Comment by owopeachy** [comment] 2024-02-27 06:58
Sorry, but whats the solution then? And this issue is not just github mods, it happens with modrinth and curse too. Why is the program deciding for the user whats best for them?

**Comment by theRookieCoder** [comment] 2024-02-28 16:42
I'm sorry I misunderstood what you had originally written.

Currently the program pretty much expects that the mod author properly specifies what Minecraft versions and mod loaders the file works with. The ignore game versions flag currently just uses the latest file that's compatible with the mod loader, which doesn't provide much flexibility. A more robust solution for your problem is provided in #155.
